db_manager/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^xiaoxue/$', views.love, name='love'),
    url(r'^detail/$', views.detail, name='detail'),
    url(r'^projects/$', views.group_member, name='group_member'),
    url(r'^projects/finish/$', views.finish, name='finish'),
    url(r'^projects/add/$', views.add_project, name='add_project'),
    url(r'^projects/quit/$', views.quit_project, name='quit_project'),
    url(r'^personal/$', views.personal_project, name='personal_project'),
    url(r'^register/$', views.register_with_project, name='register_with_project'),
    url(r'^unregister/$', views.unregister, name='unregister'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

sudu6770/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from sudu6770 import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sudu6770/', include('db_manager.urls', namespace='db_manager')),
]

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SUDU</title>
</head>
<body>
    <h1><strong>SUDU Project Management System</strong></h1>
        <p><strong>SUDU</strong> is the abbreviation of <i>SU</i>peruser <i>DU</i>e.</p>
        <p>We want to develop a management system to manage our projects when in teamwork.</p>
        <p>Also, we want to accelerate the project by providing seamless teamwork toolbelt.</p>
        <p style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif"><i>Here comes our prototype.</i></p>

    <h2><strong>Team Member</strong></h2>
    <h3>iOS Frontend</h3>
        <ul>
            <li><a href="http://www.ee.columbia.edu/">Xiwei Feng</a></li>
            <li><a href="http://www.ee.columbia.edu/">Zhaopeng Yuan</a></li>
        </ul>
    <h3>Django&Heroku Backend</h3>
        <ul>
            <li><a href={% url 'db_manager:love' %}>Guihao Liang</a></li>
        </ul>
    <p><a href={% url "db_manager:detail" %}>HOW TO USE</a></p>
    <img src="http://olivierlacan.com/images/wee-bey.gif">

</body>
</html>